apiVersion: batch/v1
kind: Job
metadata:
  name: inspect-resource
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: pytorch
          # https://hub.docker.com/r/pytorch/pytorch/tags
          # https://cloud.google.com/deep-learning-containers/docs/choosing-container
          image: gcr.io/deeplearning-platform-release/pytorch-gpu.1-12
          resources:
            limits:
              cpu: "4"
              nvidia.com/gpu: "1"
            requests:
              cpu: "4"
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
          - |
            python -V && nvidia-smi
      nodeSelector:
        cloud.google.com/gke-nodepool: gpu-pool
      restartPolicy: Never

