apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-simple
spec:
  template:
    metadata:
      labels:
        app: pytorch-simple
    spec:
      containers:
        - name: pytorch
          image: docker.io/kubeflowkatib/pytorch-mnist:v1beta1-45c5727
          resources:
            limits:
              cpu: "4"
              nvidia.com/gpu: "1"
            requests:
              cpu: "4"
          imagePullPolicy: Always
          command:
            - "python3"
            - "/opt/pytorch-mnist/mnist.py"
            - "--epochs=1"
      nodeSelector:
        cloud.google.com/gke-nodepool: gpu-pool
      restartPolicy: Never

