apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-mnist
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: pytorch
          image: gcr.io/sky-burst/skyburst:latest
          resources:
            limits:
              cpu: "12"
              nvidia.com/gpu: "1"
            requests:
              cpu: "12"
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
          - |
            python /tasks/pytorch-mnist.py
      nodeSelector:
        cloud.google.com/gke-nodepool: gpu-pool
      restartPolicy: Never
